theme = "space-villain"
icons = "awesome5"

[[block]]
block = "focused_window"
max_width = 96
show_marks = "visible"

[[block]]
block = "pacman"
interval = 600
format = "{pacman} + {aur} = {both} updates available"
format_singular = "{both} update available"
format_up_to_date = "system up to date"
critical_updates_regex = "(linux|linux-lts|linux-zen)"
## aur_command should output available updates to stdout (ie behave as echo -ne "update\n")
aur_command = "paru -Qua"
# pop-up a menu showing the available updates. Replace wofi with your favourite menu command.
on_click = "fakeroot pacman -Qu --dbpath /tmp/checkup-db-mwait/ | yofi dialog"

[[block]]
block = "kdeconnect"
on_click = "kdeconnect-sms"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0
##NOTE: doesn't display all files (due to insufficient perms to view root-owned files, I think)
on_click = "alacritty -e diskonaut -a /"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1
format = "{utilization} {barchart}"

[[block]]
block = "load"
interval = 1
format = "{1m}"
on_click = "alacritty -e btm"

[[block]]
block = "net"
format = "{ssid} {signal_strength} [{speed_up;K*B}/{speed_down;K*B}]"
interval = 3
hide_inactive = true
on_click = "alacritty -e bandwhich"

#TODO: add bluetooth block and only show if a device is connected

#TODO: display external monitor brightness, if even possible
#[[block]]
#block = "backlight"
#minimum = 0
#maximum = 100
#cycle = [100, 50, 0, 50]

[[block]]
block = "sound"
step_width = 1
headphones_indicator = true
on_click = "pavucontrol"

[[block]]
block = "music"
buttons = ["prev", "play", "next"]
format = "{player} (/{avail}) {artist} - {title}"
dynamic_width = false
marquee_speed = 0.15
marquee_interval = 2
max_width = 63

[[block]]
block = "time"
interval = 1
format = "%a %y/%m/%d %H:%M:%S"

[[block]]
block = "uptime"
#interval = 1
